dist: focal

language: python

python:
          - "3.8"

install:
          - pip install flask

script:
          - python -m unittest -v test

provider: heroku
api_key: HEROKU_API_KEY
edge: true
app: cloud-devops
on:
        branch: master
